### ISSUE TITLE
Fabric 2.0.0 (now with Python 3 support)

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/fabric-feedstock#10]
Recently Fabric 2.0.0 was released, which included Python 2/3 support. 🎉 Would be great to get it into conda-forge.

**Comment by jakirkham** [comment]
Side note: Seems the bot didn't send an update PR.

cc @CJ-Wright

**Comment by CJ-Wright** [comment]
Hmm I'll try to take a look by Thursday.

**Comment by setu4993** [comment]
Closing this since this is now done: https://github.com/conda-forge/fabric-feedstock/pull/14
