### ISSUE TITLE
python 35 and 36 for fabric 1.13.2

### ISSUE THREAD

**Issue by sannykr** [conda-forge/fabric-feedstock#9]
Could you please retrigger the build so that python 35 and 36 files become available on conda-forge.

**Comment by sannykr** [comment]
@synapticarbors : Could you please tell me how I can build for python 35 and 36 versions. I can see a pull request for rerendering the feedstock that has not been merged yet.

**Comment by synapticarbors** [comment]
It's up to @pmlandwehr or someone with privileges on this repo to merge the pull request.

**Comment by pmlandwehr** [comment]
Per the [description](https://github.com/fabric/fabric/blob/master/README.rst), `fabric` is only for `py27`; the recipe actually skips `py3k` builds for just this reason. If you want `fabric` for `py3k`, check out [`fabric3`](https://github.com/conda-forge/fabric3-feedstock).

**Comment by jakirkham** [comment]
Yep, `fabric` 1 is Python 2 only. `fabric` 2 is Python 2/3. Should work on getting that out if we'd like to get Python 3 support.

xref: https://github.com/conda-forge/fabric-feedstock/issues/10
